"""delete hours to backlog and refactor notes

Revision ID: 3ec49b6f9031
Revises: de610962d881
Create Date: 2026-02-18 03:03:16.500498

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3ec49b6f9031'
down_revision: Union[str, None] = 'de610962d881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### create the ENUM type first ###
    gamepriority = postgresql.ENUM('low', 'medium', 'high', name='gamepriority')
    gamepriority.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game_backlog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(
        'game_backlog',
        'priority',
        type_=gamepriority,
        existing_type=sa.VARCHAR(),
        existing_nullable=True,
        postgresql_using='priority::gamepriority'  # <-- important
    )
    op.drop_column('game_backlog', 'hours_played')
    op.drop_column('game_backlog', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_backlog', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('game_backlog', sa.Column('hours_played', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column(
        'game_backlog',
        'priority',
        existing_type=postgresql.ENUM('low', 'medium', 'high', name='gamepriority'),
        type_=sa.VARCHAR(),
        existing_nullable=True
    )
    op.drop_table('game_notes')
    gamepriority = postgresql.ENUM('low', 'medium', 'high', name='gamepriority')
    gamepriority.drop(op.get_bind())
    # ### end Alembic commands ###
