"""add_link_to_videogames

Revision ID: 498b1598216b
Revises: 4fb14808d7ee
Create Date: 2026-02-19 02:10:22.797821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498b1598216b'
down_revision: Union[str, None] = '4fb14808d7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_backlog', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_backlog', 'link')
    # ### end Alembic commands ###
