"""remove_id_tomanytomany_table

Revision ID: 8e7a54639f2b
Revises: 3ec49b6f9031
Create Date: 2026-02-18 20:24:29.235074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e7a54639f2b'
down_revision: Union[str, None] = '3ec49b6f9031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drawing_collections_id'), table_name='drawing_collections')
    op.drop_table('drawing_collections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawing_collections',
    sa.Column('drawing_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('drawing_collections_collection_id_fkey')),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], name=op.f('drawing_collections_drawing_id_fkey')),
    sa.PrimaryKeyConstraint('drawing_id', 'collection_id', 'id', name=op.f('drawing_collections_pkey'))
    )
    op.create_index(op.f('ix_drawing_collections_id'), 'drawing_collections', ['id'], unique=False)
    # ### end Alembic commands ###
