"""add_collection_link_on_game

Revision ID: 9a44f3995bd7
Revises: 392a00fa931a
Create Date: 2026-02-18 20:47:23.943691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a44f3995bd7'
down_revision: Union[str, None] = '392a00fa931a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_backlog', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game_backlog', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_backlog', type_='foreignkey')
    op.drop_column('game_backlog', 'collection_id')
    # ### end Alembic commands ###
