"""add_dev_and_publisher_to_games

Revision ID: a1ecb66b0df0
Revises: 9a44f3995bd7
Create Date: 2026-02-18 21:48:47.904999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ecb66b0df0'
down_revision: Union[str, None] = '9a44f3995bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_backlog', sa.Column('developer', sa.String(), nullable=True))
    op.add_column('game_backlog', sa.Column('publisher', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_backlog', 'publisher')
    op.drop_column('game_backlog', 'developer')
    # ### end Alembic commands ###
