"""change base model for add created and update date

Revision ID: d629314fe1d4
Revises: db1c931c770b
Create Date: 2026-02-17 23:48:41.163218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd629314fe1d4'
down_revision: Union[str, None] = 'db1c931c770b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_backlog',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('wishlist', 'backlog', 'installed', 'next_up', 'playing', 'on_hold', 'finished_main', 'finished_100', 'finished_dlc', 'dropped', 'soft_dropped', name='gamestatus'), nullable=False),
    sa.Column('platform', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('genre', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('hours_played', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_backlog_id'), 'game_backlog', ['id'], unique=False)
    op.add_column('guestbook_entries', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('guestbook_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('quotes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('quotes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.alter_column('quotes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('quotes', 'updated_at')
    op.alter_column('guestbook_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('guestbook_entries', 'updated_at')
    op.drop_index(op.f('ix_game_backlog_id'), table_name='game_backlog')
    op.drop_table('game_backlog')
    # ### end Alembic commands ###
